title: "Korean Adoptees Together"
description: "Nonprofit Organization Supporting Korean Adoptees"
url: "https://kat-inc-fl.github.io"
baseurl: ""

# Theme and plugins
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Site settings
future: true

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Events"
    url: /events/

# Social media (for Minima footer and SEO)
facebook_username: koreanadopteestogether
instagram_username: koreanadopteestogether
linkedin_username: koreanadopteestogether

# Facebook-specific settings for Open Graph
facebook:
  publisher: https://www.facebook.com/koreanadopteestogether
