name: Sync Google Sheets to YAML

on:
  workflow_dispatch:  # Manual trigger

jobs:
  sync-sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Fetch and convert Google Sheets data
        run: |
          python .github/scripts/sync_sheets.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/resources.yml
          git diff --staged --quiet || git commit -m "Auto-update resources from Google Sheets [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
